name: Docker Compose CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unit tests run
        uses: cloudposse/github-action-docker-compose-test-run@0.2.0
        with:
          file: "./docker-compose-test.yml"
          service: web_run_unit_tests
          command: ''

      - name: e2e tests run
        uses: cloudposse/github-action-docker-compose-test-run@0.2.0
        with:
          file: "./docker-compose-test.yml"
          service: web_run_e2e_tests
          command: ''


  lint:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Super-Linter
        uses: super-linter/super-linter@v5.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
